export const ERROR_CODE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  // Common error start with prefix 100x
  INVALID_PAGE_OPTIONS: 'COMMON_0001',
  VALIDATION_FAILED: 'COMMON_0002',
  HTTP_NOT_FOUND: 'COMMON_0003',
  HTTP_UNHANDLED: 'COMMON_0004',
  HTTP_UNAUTHORIZED: 'COMMON_0005',
  // File error start with prefix 400x
  FILE_NOT_FOUND: 'FILE_4001',
  READ_FILE_ERROR: 'FILE_4002',
  SAVE_FILE_ERROR: 'FILE_4003',
  GET_FILE_SYSTEM_STAT_ERROR: 'FILE_4004',
  FILE_IS_REQUIRED: 'FILE_4005',
  MAX_FILE_SIZE: 'FILE_4006',
  INVALID_FILE_TYPE: 'FILE_4007',
};
